name: "Deploy dictionary app into GH pages"

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: "Install Node Version"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: "Install dependencies"
        run: npm i

      - name: "Linter"
        run: npm run lint

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: linter

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: "Install Node Version"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: "Install dependencies"
        run: npm i

      - name: "Configure GH page"
        uses: actions/configure-pages@v3

      - name: "Build"
        run: npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/

      - name: "Deploy GH page"
        uses: actions/deploy-pages@v1
        id: deployment
